name: cobm_atendimento
description: "App mobile Flutter para gerenciamento de atendimento de uma casa espírita."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8

  # State management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # Backend
  supabase_flutter: ^2.8.4

  # Navigation
  go_router: ^14.6.3

  # Models
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # Code generation
  build_runner: ^2.4.14
  freezed: ^2.5.7
  riverpod_generator: ^2.6.3
  json_serializable: ^6.9.3

  # Tests
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
